const langList = {
    eng: {
        siteTitle: "Game of Life | Cellular Automaton",
        gameLife: "Game of Life",
        info: "Info",
        run: "Run simulation",
        pause: "Pause simulation",
        randomize: "Random generation",
        settings: "Settings",
        themeColor: "Theme color",
        lightTheme: "Light theme",
        darkTheme: "Dark theme",
        universeBound: "Universe bound (modifying this value resets history)",
        bound: "Bound",
        cellSize: "Cell size (modifying this value resets history)",
        size: "Size",
        speedRange: "Generation speed",
        speed: "Speed",
        toggleGrid: "Toggle grid",
        prevGen: "Previous generation",
        nextGen: "Next generation",
        resetSettings: "Reset settings (bound, size, speed",
        reset: "Reset",
        clearCells: "Clear cells",
        clear: "Clear",
        readMore: "Read more...",
        wikiLink: "https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life"
    },
    esp: {
        siteTitle: "Juego de la Vida | Autómata Celular",
        gameLife: "Juego de la Vida",
        info: "Info",
        run: "Correr simulación",
        pause: "Pausar simulación",
        randomize: "Generación aleatoria",
        settings: "Ajustes",
        themeColor: "Color de tema",
        lightTheme: "Tema claro",
        darkTheme: "Tema oscuro",
        universeBound: "Límite del universo (modificar este valor resetea la historia)",
        bound: "Límite",
        cellSize: "Tamaño de celda (modificar este valor resetea la historia)",
        size: "Tamaño",
        speedRange: "Velocidad de generación",
        speed: "Vel.",
        toggleGrid: "Alternar grilla",
        prevGen: "Generación anterior",
        nextGen: "Generación siguiente",
        resetSettings: "Restablecer ajustes (límite, tamaño, velocidad)",
        reset: "Rest.",
        clearCells: "Vaciar celdas",
        clear: "Vaciar",
        readMore: "Leer más...",
        wikiLink: "https://es.wikipedia.org/wiki/Juego_de_la_vida"
    }
}

export default langList